apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: said-dev
  labels:
    app: backend
spec:
  replicas: 2 #create 2 pods
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred #secret to pull image
      containers:
        - name: backend
          image: ghcr.io/saidalhendi/backend:v0.0.1 #github image
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: mongodb://praxis-form-mongodb.praxis.svc.cluster.local:27017/praxis-said #db image
            - name: JWT_SECRET # env
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: ADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: ADMIN_DEFAULT_PASSWORD
            - name: JWT_EXP_MINUTES
              value: '120'
          ports:
            - containerPort: 8080
