apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }} #secret to pull image
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repo}}:{{ .Values.backend.image.tag}}"
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
            # value: mongodb://praxis-form-mongodb.praxis.svc.cluster.local:27017/praxis-said #db image
            - name: JWT_SECRET # env
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: ADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: ADMIN_DEFAULT_PASSWORD
            - name: JWT_EXP_MINUTES
              value: '120'
          ports:
            - containerPort: 8080
