---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: said-dev
spec:
  encryptedData:
    ADMIN_DEFAULT_PASSWORD: AgBTViCsBAtcHCCmxtKHBaUPIKuVQNnlJ9GvTes94HQVL8Dih2LCBqlQi5IJiVilnAiVPcXJPiN0qHDZ7AzN5pWCRfne8rd2H3cJt91coCFXxfFDw7pLj26+iMPMFYkoJXJ1/VBzmpceEJJu7Z1v8DslnhPPRC0PxzL9gFhsiP/02vpt7ewdrTa+gfVdwqaLDNZ30pH6uekWddblh0OMQEgzvPZMDD0DfZrGg0XdK9f3bZ9HBdSZYmJoXTTzZgETeD47rS++K/VIQKK2Z5q+Lr/J0oQkwNKGmJqpKIXJS2cZIhvQUMtp80hbk2ko1imdZ55ejFgMfY/8U2v5dMoX03M/64frjsFFx43Ri2le2ReMl6SL/ah4vIu/O8dpmDqMq8QBDKgigUZV0ADYJNSHMArMA/pRyuTdBXPHaNT1TONVDI3Ghq01+MmUmZnssST+NV2W8gg8lPjIkuxz6D1av/mkaoltTkgYdvb2ONpxUGC64606lulrdtFkQVYrcyP1fLg4KOU3s/3NhhK3MH4Q8ukMldw/cglf8+mSbWcueb9oRVJGZXd34zybAryWD9HcSvt9NifRb5HRFvrJKRyVNVQtgtGICK9V7XOoGu1lBP09ntnIPwDZGcKay+oyYpQmqz/b47vClBMn7ETSgZsE7buvmX9WWEcJE8W7jwLA6UMVUSyTlCNPGMHMMzTd32CwtSeNsBlve2FN/t7EPLqjcEfd
    JWT_SECRET: AgA750AjEQGTTtvustvlyGPt53E8vXpHHbeIID5MWJR3QrLeiPKRMW6RNSG9pFVuajazLwoTAAXJokN5tmE+h2yvXpPzOq6SnJwk32IXAB0+r8XPQCsfXwjB2JbLDYevB04E6BF7mbjSu6B9CFzVV2XWAQ306ZWO8DeJ5M8uwGfugQp9q7ritFn+/ChTW3UYFNG1/HG1WS5GOzGgfkJ665OOxkTxr5YRalyn88PAMMiMaAnjQaZPN21L7/QcqShcY3NOtEMaR38nWe7UdVAUpsncdfIErZKjXKqCzapmwyINbTHuWyh5fTKcrGUgeZCJU2HxOVRLUJn9JPg1+Cv7MPmYYRoy2Pdq6r9fR3B/HVfNyQ8Vt5iL0IDJQVEhuprsNRgWNmgvdsg9dsz679DJDIKb9y1yx4p4gQ+cGfE95tGF8ud2xc6XzJhxDCrpJys8S+h567mD58u2lxzd/qyk0BuSZRCjByNUpRNqS4ljvX7vu+nyJQFZHjNloWpl4doOkBXYxacoFA/say4BXz3oq8kE+gU7L4OBT3FQMF3KTO98UOCggdUCLhJIVOr75zdgQFMUuzrEfwGQx7qeYpMOhhF9YLRZcj4esO8Aje/EmS7ONi+H1wPddkp/p8i0e941TuCq+gioPEokUIDAm0aHsOJvtCxcJP9annljjYsLPixlCgvO8fGy4Vuh1HkN/dEnoDGUyYvB2YGF12gUitXDrZvDq+c0/e9uFk37YCJA5oSju+6umyDltOd5avzn+V8Ud1BnQO79gmw8u4MdZbYl+aAC
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: said-praxis-form
        meta.helm.sh/release-namespace: said-dev
      labels:
        app.kubernetes.io/managed-by: Helm
      name: backend-secret
      namespace: said-dev
    type: Opaque
