---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: said-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCsyGgUsx2OL2JTS3lbUYJcUzOdyoXVB8LU7erHnfy5b+gLCa3OAmQ7Em4JMqerqwmdQTzyVqmrb69i/bh8YACgDE2nX/A9sVdkIK1AWtFIZ/j8LGMIkoH+F0dtSoBk7y8N8s3ymRCGDkm8pPsXyfjiYaw10NFHminJ75SbOfg+mOBhwCymz1w+gXZ1UbZeBMm3fJILLURQre7uuPT6bSxtgYqel7Fjq0VAF9UWKWn1yhgonipJXrxfw2n5sa9y4ivdAHatEM5bJBppdlnahNSP+7NvWuTlsAjxe4CnZZatwVzRvb+wbL/FwjSWYtMTPP0Xhj+9uIByLiCl9X6BVL3Ef2C1yTcbtOf/8N6wipe6JgO3I0nZbEZGSgZ4+RnSGdDMBjlOSY08/yCIqspT+J0tCxYsYwqXi15rrjcpfCn5pyZvpwxRsspK6DwG6wZRnMg+nl+bnTautx7wnsgVFZuOwcxK9xQX6DsgeK/KFRtpKoLlsRYdO4Se98XSfKFTJ06hiYMCsPAUQsbN7DhFdqKQioi5k0KIbktWanZzgYvcjHFHO2aEUwGsKzPDNpJCZDbZSpdjf6J2TD5PqsQKSQe5wbycsV4SceIR80RfAxMkNDzDqbbSYBNs/1JrkrboScrTVgOyvZW92p1Y0Pt4C9HsRlegPuj3SSGPY9QSBw8Pz7YR1qRJ3oOSQW6sBnr9DGUpviDsbtGcSU2nC2NeHoH0VBC77Jf7ncOAqtCVuOy7592esyHZ3OTbMi9bgT2FYUBAf44Q1+aJa0wBgqUgwaPqacTsoKe2JsdkmdtHdz2nf1HnhbD5gFIt5XeoIe/sH3a2wMbM/7RwY90Mv+DH2z4ZeiFe0CvSd2VPiAP7+oO3kqsycMavfG94xZsFhVOfcCGG6kqi/ng3B4qJjU3338NJXOJWCc5se2Z37Y67N+UYBNfqtA3iUIJe
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: said-praxis-form
        meta.helm.sh/release-namespace: said-dev
      labels:
        app.kubernetes.io/managed-by: Helm
      name: regcred
      namespace: said-dev
    type: kubernetes.io/dockerconfigjson
